# Generated by Django 2.2.12 on 2020-04-13 13:16

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', jsonfield.fields.JSONField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.FormSchema')),
            ],
        ),
    ]
